#!/bin/bash

. etc/compare_files.sh
. etc/format.sh

printf '%s\n' 'Removing old csv files'
rm data/files/*.csv 2> /dev/null

printf '%s\n' 'Formatting code files before compiling'
format_files

printf '%s\n' 'Compiling C program'
gcc src/sorting/main.c -o main.out

printf '%s\n' 'Executing program'
./main.out

printf '%s\n' 'Checking if new files are correctly sorted'
check=$(compare)

if [[ "$check" == '0' ]]; then
  printf '%s\n' 'Generating comparisons and moves graphs'

  cd data
  python3 data_generator.py
  cd ..

  printf '%s\n' 'Done!'
else
  printf 'Execution aborted due to errors in sorting:'
  ## Setting IFS to space and newline characters
  IFS=' 
  '
  info=($check)
  for ((i = 0; i < ${#info[@]}; i += 2)); do
    month=${info[$i]}

    IFS='/.'
    alg_path=(${info[$(($i + 1))]})
    alg=${alg_path[2]}

    printf '%s\n' "$alg produced a non-sorted file in month $month"
  done
fi
